version: '3.8'

services:
  milvus:
    image: milvusdb/milvus:latest
    container_name: milvus
    environment:
      - "TZ=UTC"
    ports:
      - "19530:19530"
      - "9091:9091"
    volumes:
      - ./volumes/milvus/db:/var/lib/milvus/db
      - ./volumes/milvus/conf:/var/lib/milvus/conf
      - ./volumes/milvus/logs:/var/lib/milvus/logs
      - ./volumes/milvus/wal:/var/lib/milvus/wal
